version: '3'

services:
  postgres:
    build:
      context: ./postgres
      dockerfile: ./Dockerfile
    image: postgres_uuid_v7:16
    restart: always
    env_file:
      - "../dev.env"
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
